image: ubuntu:20.04

build-job:
  stage: build
  script:
    - echo "Hola, $GITLAB_USER_LOGIN!"
  only:
    - master

test-job:
  stage: test
  script:
    - export FTP_SERVER=$FTP_SERVER
    - echo $FTP_SERVER
    - echo "$FTP_SERVER"
    - echo "Servidor, $FTP_SERVER"
  only: 
    - master


deploy-job:
 stage: deploy
 script:
   - apt-get update -qy
   - apt-get install -y lftp
  #  - apt-get install -y apt-transport-https
  #  - apt-get update
  #  - apt-get install -y aspnetcore-runtime-6.0
  #  - dotnet restore
  #  - dotnet publish -c release
   - lftp -c "set ftp:ssl-allow no; open $FTP_SERVER; user $FTP_USERNAME $FTP_PASSWORD; mirror --ignore-time --parallel=10  ./bin/release/netcoreapp3.1/publish ./public_html; bye"
 only:
   - master